default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", "developer") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "developer") %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "lms_development") %>

test:
  <<: *default
  database: lms_test

production:
  <<: *default
  database: lms_production

